//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comun.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comun.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave de acceso del usuario contiene un valor no permitido por el sistema o no coincide con la longitud de caracteres mayor a 4 dígitos..
        /// </summary>
        internal static string CLAVE_USUARIO_DEFAULT {
            get {
                return ResourceManager.GetString("CLAVE_USUARIO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad Fecha del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string FECHA_DEFAULT {
            get {
                return ResourceManager.GetString("FECHA_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad IdCategoria del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_CATEGORIA_DEFAULT {
            get {
                return ResourceManager.GetString("ID_CATEGORIA_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad IdCompra del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_COMPRA_DEFAULT {
            get {
                return ResourceManager.GetString("ID_COMPRA_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad Id del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_DEFAULT {
            get {
                return ResourceManager.GetString("ID_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad IdEmpleado del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_EMPLEADO_DEFAULT {
            get {
                return ResourceManager.GetString("ID_EMPLEADO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad IdMateriaPrima del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_MATERIA_PRIMA_DEFAULT {
            get {
                return ResourceManager.GetString("ID_MATERIA_PRIMA_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad IdMunicipio del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_MUNICIPIO_DEFAULT {
            get {
                return ResourceManager.GetString("ID_MUNICIPIO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad IdProducto del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_PRODUCTO_DEFAULT {
            get {
                return ResourceManager.GetString("ID_PRODUCTO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad IdProveedor del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_PROVEEDOR_DEFAULT {
            get {
                return ResourceManager.GetString("ID_PROVEEDOR_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad IdRol del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_ROL_DEFAULT {
            get {
                return ResourceManager.GetString("ID_ROL_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad IdUsuario del objeto tiene un valor por defecto, nulo, o no permitido..
        /// </summary>
        internal static string ID_USUARIO_DEFAULT {
            get {
                return ResourceManager.GetString("ID_USUARIO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario contiene un valor no permitido por el sistema o no coincide con la longitud de caracteres de entre 4 a 50 dígitos..
        /// </summary>
        internal static string NOMBRE_USUARIO_DEFAULT {
            get {
                return ResourceManager.GetString("NOMBRE_USUARIO_DEFAULT", resourceCulture);
            }
        }
    }
}
