namespace Ice.Presentacion.Principal
{
    partial class FrmPrincipal
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuAnimatorNS.Animation animation1 = new Bunifu.UI.WinForms.BunifuAnimatorNS.Animation();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmPrincipal));
            this.PnlTopBar = new System.Windows.Forms.Panel();
            this.PbMenu = new System.Windows.Forms.PictureBox();
            this.PnlSideBar = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.BtnVentas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnClientes = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnUsuarios = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnRoles = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnEmpleados = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnProductos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnMateriasPrimas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCategoriasProductos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnProveedores = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCompras = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SideBarTransition = new Bunifu.UI.WinForms.BunifuTransition(this.components);
            this.PnlPrincipal = new System.Windows.Forms.Panel();
            this.PnlTopBar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PbMenu)).BeginInit();
            this.PnlSideBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // PnlTopBar
            // 
            this.PnlTopBar.Controls.Add(this.PbMenu);
            this.SideBarTransition.SetDecoration(this.PnlTopBar, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.PnlTopBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.PnlTopBar.Location = new System.Drawing.Point(0, 0);
            this.PnlTopBar.Name = "PnlTopBar";
            this.PnlTopBar.Size = new System.Drawing.Size(885, 27);
            this.PnlTopBar.TabIndex = 0;
            // 
            // PbMenu
            // 
            this.PbMenu.Cursor = System.Windows.Forms.Cursors.Hand;
            this.SideBarTransition.SetDecoration(this.PbMenu, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.PbMenu.Dock = System.Windows.Forms.DockStyle.Left;
            this.PbMenu.Image = global::Ice.Properties.Resources.menu_burger;
            this.PbMenu.Location = new System.Drawing.Point(0, 0);
            this.PbMenu.Name = "PbMenu";
            this.PbMenu.Size = new System.Drawing.Size(47, 27);
            this.PbMenu.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PbMenu.TabIndex = 0;
            this.PbMenu.TabStop = false;
            this.PbMenu.Click += new System.EventHandler(this.PbMenu_Click);
            // 
            // PnlSideBar
            // 
            this.PnlSideBar.AutoScroll = true;
            this.PnlSideBar.BackColor = System.Drawing.Color.Transparent;
            this.PnlSideBar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PnlSideBar.BackgroundImage")));
            this.PnlSideBar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.PnlSideBar.BorderRadius = 15;
            this.PnlSideBar.Controls.Add(this.BtnVentas);
            this.PnlSideBar.Controls.Add(this.BtnClientes);
            this.PnlSideBar.Controls.Add(this.BtnUsuarios);
            this.PnlSideBar.Controls.Add(this.BtnRoles);
            this.PnlSideBar.Controls.Add(this.BtnEmpleados);
            this.PnlSideBar.Controls.Add(this.BtnProductos);
            this.PnlSideBar.Controls.Add(this.BtnMateriasPrimas);
            this.PnlSideBar.Controls.Add(this.BtnCategoriasProductos);
            this.PnlSideBar.Controls.Add(this.BtnProveedores);
            this.PnlSideBar.Controls.Add(this.BtnCompras);
            this.SideBarTransition.SetDecoration(this.PnlSideBar, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.PnlSideBar.Dock = System.Windows.Forms.DockStyle.Left;
            this.PnlSideBar.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(234)))), ((int)(((byte)(175)))));
            this.PnlSideBar.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(238)))), ((int)(((byte)(129)))), ((int)(((byte)(167)))));
            this.PnlSideBar.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(238)))), ((int)(((byte)(129)))), ((int)(((byte)(140)))));
            this.PnlSideBar.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(185)))), ((int)(((byte)(249)))));
            this.PnlSideBar.Location = new System.Drawing.Point(0, 27);
            this.PnlSideBar.Name = "PnlSideBar";
            this.PnlSideBar.Quality = 10;
            this.PnlSideBar.Size = new System.Drawing.Size(228, 476);
            this.PnlSideBar.TabIndex = 1;
            this.PnlSideBar.Visible = false;
            // 
            // BtnVentas
            // 
            this.BtnVentas.AllowAnimations = true;
            this.BtnVentas.AllowMouseEffects = true;
            this.BtnVentas.AllowToggling = false;
            this.BtnVentas.AnimationSpeed = 200;
            this.BtnVentas.AutoGenerateColors = false;
            this.BtnVentas.AutoRoundBorders = false;
            this.BtnVentas.AutoSizeLeftIcon = true;
            this.BtnVentas.AutoSizeRightIcon = true;
            this.BtnVentas.BackColor = System.Drawing.Color.Transparent;
            this.BtnVentas.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnVentas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnVentas.BackgroundImage")));
            this.BtnVentas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVentas.ButtonText = "Ventas";
            this.BtnVentas.ButtonTextMarginLeft = 0;
            this.BtnVentas.ColorContrastOnClick = 45;
            this.BtnVentas.ColorContrastOnHover = 45;
            this.BtnVentas.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnVentas.CustomizableEdges = borderEdges1;
            this.SideBarTransition.SetDecoration(this.BtnVentas, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnVentas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnVentas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnVentas.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnVentas.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnVentas.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnVentas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnVentas.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnVentas.ForeColor = System.Drawing.Color.White;
            this.BtnVentas.IconLeft = global::Ice.Properties.Resources.search_dollar;
            this.BtnVentas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnVentas.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnVentas.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnVentas.IconMarginLeft = 11;
            this.BtnVentas.IconPadding = 10;
            this.BtnVentas.IconRight = null;
            this.BtnVentas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnVentas.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnVentas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnVentas.IconSize = 25;
            this.BtnVentas.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnVentas.IdleBorderRadius = 0;
            this.BtnVentas.IdleBorderThickness = 0;
            this.BtnVentas.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnVentas.IdleIconLeftImage = global::Ice.Properties.Resources.search_dollar;
            this.BtnVentas.IdleIconRightImage = null;
            this.BtnVentas.IndicateFocus = false;
            this.BtnVentas.Location = new System.Drawing.Point(0, 354);
            this.BtnVentas.Name = "BtnVentas";
            this.BtnVentas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnVentas.OnDisabledState.BorderRadius = 15;
            this.BtnVentas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVentas.OnDisabledState.BorderThickness = 1;
            this.BtnVentas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnVentas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnVentas.OnDisabledState.IconLeftImage = null;
            this.BtnVentas.OnDisabledState.IconRightImage = null;
            this.BtnVentas.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnVentas.onHoverState.BorderRadius = 15;
            this.BtnVentas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVentas.onHoverState.BorderThickness = 1;
            this.BtnVentas.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnVentas.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnVentas.onHoverState.IconLeftImage = null;
            this.BtnVentas.onHoverState.IconRightImage = null;
            this.BtnVentas.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnVentas.OnIdleState.BorderRadius = 15;
            this.BtnVentas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVentas.OnIdleState.BorderThickness = 1;
            this.BtnVentas.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnVentas.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnVentas.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.search_dollar;
            this.BtnVentas.OnIdleState.IconRightImage = null;
            this.BtnVentas.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnVentas.OnPressedState.BorderRadius = 15;
            this.BtnVentas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVentas.OnPressedState.BorderThickness = 1;
            this.BtnVentas.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnVentas.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnVentas.OnPressedState.IconLeftImage = null;
            this.BtnVentas.OnPressedState.IconRightImage = null;
            this.BtnVentas.Size = new System.Drawing.Size(228, 39);
            this.BtnVentas.TabIndex = 9;
            this.BtnVentas.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnVentas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnVentas.TextMarginLeft = 0;
            this.BtnVentas.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnVentas.UseDefaultRadiusAndThickness = true;
            this.BtnVentas.Click += new System.EventHandler(this.BtnVentas_Click);
            // 
            // BtnClientes
            // 
            this.BtnClientes.AllowAnimations = true;
            this.BtnClientes.AllowMouseEffects = true;
            this.BtnClientes.AllowToggling = false;
            this.BtnClientes.AnimationSpeed = 200;
            this.BtnClientes.AutoGenerateColors = false;
            this.BtnClientes.AutoRoundBorders = false;
            this.BtnClientes.AutoSizeLeftIcon = true;
            this.BtnClientes.AutoSizeRightIcon = true;
            this.BtnClientes.BackColor = System.Drawing.Color.Transparent;
            this.BtnClientes.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnClientes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnClientes.BackgroundImage")));
            this.BtnClientes.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnClientes.ButtonText = "Clientes";
            this.BtnClientes.ButtonTextMarginLeft = 0;
            this.BtnClientes.ColorContrastOnClick = 45;
            this.BtnClientes.ColorContrastOnHover = 45;
            this.BtnClientes.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnClientes.CustomizableEdges = borderEdges2;
            this.SideBarTransition.SetDecoration(this.BtnClientes, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnClientes.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnClientes.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnClientes.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnClientes.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnClientes.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnClientes.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnClientes.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnClientes.ForeColor = System.Drawing.Color.White;
            this.BtnClientes.IconLeft = global::Ice.Properties.Resources.users_alt;
            this.BtnClientes.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnClientes.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnClientes.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnClientes.IconMarginLeft = 11;
            this.BtnClientes.IconPadding = 10;
            this.BtnClientes.IconRight = null;
            this.BtnClientes.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnClientes.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnClientes.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnClientes.IconSize = 25;
            this.BtnClientes.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnClientes.IdleBorderRadius = 0;
            this.BtnClientes.IdleBorderThickness = 0;
            this.BtnClientes.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnClientes.IdleIconLeftImage = global::Ice.Properties.Resources.users_alt;
            this.BtnClientes.IdleIconRightImage = null;
            this.BtnClientes.IndicateFocus = false;
            this.BtnClientes.Location = new System.Drawing.Point(0, 315);
            this.BtnClientes.Name = "BtnClientes";
            this.BtnClientes.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnClientes.OnDisabledState.BorderRadius = 15;
            this.BtnClientes.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnClientes.OnDisabledState.BorderThickness = 1;
            this.BtnClientes.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnClientes.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnClientes.OnDisabledState.IconLeftImage = null;
            this.BtnClientes.OnDisabledState.IconRightImage = null;
            this.BtnClientes.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnClientes.onHoverState.BorderRadius = 15;
            this.BtnClientes.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnClientes.onHoverState.BorderThickness = 1;
            this.BtnClientes.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnClientes.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnClientes.onHoverState.IconLeftImage = null;
            this.BtnClientes.onHoverState.IconRightImage = null;
            this.BtnClientes.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnClientes.OnIdleState.BorderRadius = 15;
            this.BtnClientes.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnClientes.OnIdleState.BorderThickness = 1;
            this.BtnClientes.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnClientes.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnClientes.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.users_alt;
            this.BtnClientes.OnIdleState.IconRightImage = null;
            this.BtnClientes.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnClientes.OnPressedState.BorderRadius = 15;
            this.BtnClientes.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnClientes.OnPressedState.BorderThickness = 1;
            this.BtnClientes.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnClientes.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnClientes.OnPressedState.IconLeftImage = null;
            this.BtnClientes.OnPressedState.IconRightImage = null;
            this.BtnClientes.Size = new System.Drawing.Size(228, 39);
            this.BtnClientes.TabIndex = 8;
            this.BtnClientes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnClientes.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnClientes.TextMarginLeft = 0;
            this.BtnClientes.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnClientes.UseDefaultRadiusAndThickness = true;
            this.BtnClientes.Click += new System.EventHandler(this.BtnClientes_Click);
            // 
            // BtnUsuarios
            // 
            this.BtnUsuarios.AllowAnimations = true;
            this.BtnUsuarios.AllowMouseEffects = true;
            this.BtnUsuarios.AllowToggling = false;
            this.BtnUsuarios.AnimationSpeed = 200;
            this.BtnUsuarios.AutoGenerateColors = false;
            this.BtnUsuarios.AutoRoundBorders = false;
            this.BtnUsuarios.AutoSizeLeftIcon = true;
            this.BtnUsuarios.AutoSizeRightIcon = true;
            this.BtnUsuarios.BackColor = System.Drawing.Color.Transparent;
            this.BtnUsuarios.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnUsuarios.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnUsuarios.BackgroundImage")));
            this.BtnUsuarios.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUsuarios.ButtonText = "Usuarios";
            this.BtnUsuarios.ButtonTextMarginLeft = 0;
            this.BtnUsuarios.ColorContrastOnClick = 45;
            this.BtnUsuarios.ColorContrastOnHover = 45;
            this.BtnUsuarios.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnUsuarios.CustomizableEdges = borderEdges3;
            this.SideBarTransition.SetDecoration(this.BtnUsuarios, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnUsuarios.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnUsuarios.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUsuarios.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnUsuarios.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnUsuarios.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnUsuarios.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnUsuarios.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnUsuarios.ForeColor = System.Drawing.Color.White;
            this.BtnUsuarios.IconLeft = global::Ice.Properties.Resources.portrait;
            this.BtnUsuarios.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnUsuarios.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUsuarios.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnUsuarios.IconMarginLeft = 11;
            this.BtnUsuarios.IconPadding = 10;
            this.BtnUsuarios.IconRight = null;
            this.BtnUsuarios.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnUsuarios.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnUsuarios.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnUsuarios.IconSize = 25;
            this.BtnUsuarios.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnUsuarios.IdleBorderRadius = 0;
            this.BtnUsuarios.IdleBorderThickness = 0;
            this.BtnUsuarios.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnUsuarios.IdleIconLeftImage = global::Ice.Properties.Resources.portrait;
            this.BtnUsuarios.IdleIconRightImage = null;
            this.BtnUsuarios.IndicateFocus = false;
            this.BtnUsuarios.Location = new System.Drawing.Point(0, 276);
            this.BtnUsuarios.Name = "BtnUsuarios";
            this.BtnUsuarios.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnUsuarios.OnDisabledState.BorderRadius = 15;
            this.BtnUsuarios.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUsuarios.OnDisabledState.BorderThickness = 1;
            this.BtnUsuarios.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnUsuarios.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnUsuarios.OnDisabledState.IconLeftImage = null;
            this.BtnUsuarios.OnDisabledState.IconRightImage = null;
            this.BtnUsuarios.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnUsuarios.onHoverState.BorderRadius = 15;
            this.BtnUsuarios.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUsuarios.onHoverState.BorderThickness = 1;
            this.BtnUsuarios.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnUsuarios.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnUsuarios.onHoverState.IconLeftImage = null;
            this.BtnUsuarios.onHoverState.IconRightImage = null;
            this.BtnUsuarios.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnUsuarios.OnIdleState.BorderRadius = 15;
            this.BtnUsuarios.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUsuarios.OnIdleState.BorderThickness = 1;
            this.BtnUsuarios.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnUsuarios.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnUsuarios.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.portrait;
            this.BtnUsuarios.OnIdleState.IconRightImage = null;
            this.BtnUsuarios.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnUsuarios.OnPressedState.BorderRadius = 15;
            this.BtnUsuarios.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnUsuarios.OnPressedState.BorderThickness = 1;
            this.BtnUsuarios.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnUsuarios.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnUsuarios.OnPressedState.IconLeftImage = null;
            this.BtnUsuarios.OnPressedState.IconRightImage = null;
            this.BtnUsuarios.Size = new System.Drawing.Size(228, 39);
            this.BtnUsuarios.TabIndex = 7;
            this.BtnUsuarios.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnUsuarios.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnUsuarios.TextMarginLeft = 0;
            this.BtnUsuarios.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnUsuarios.UseDefaultRadiusAndThickness = true;
            this.BtnUsuarios.Click += new System.EventHandler(this.BtnUsuarios_Click);
            // 
            // BtnRoles
            // 
            this.BtnRoles.AllowAnimations = true;
            this.BtnRoles.AllowMouseEffects = true;
            this.BtnRoles.AllowToggling = false;
            this.BtnRoles.AnimationSpeed = 200;
            this.BtnRoles.AutoGenerateColors = false;
            this.BtnRoles.AutoRoundBorders = false;
            this.BtnRoles.AutoSizeLeftIcon = true;
            this.BtnRoles.AutoSizeRightIcon = true;
            this.BtnRoles.BackColor = System.Drawing.Color.Transparent;
            this.BtnRoles.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnRoles.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnRoles.BackgroundImage")));
            this.BtnRoles.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRoles.ButtonText = "Roles";
            this.BtnRoles.ButtonTextMarginLeft = 0;
            this.BtnRoles.ColorContrastOnClick = 45;
            this.BtnRoles.ColorContrastOnHover = 45;
            this.BtnRoles.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnRoles.CustomizableEdges = borderEdges4;
            this.SideBarTransition.SetDecoration(this.BtnRoles, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnRoles.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnRoles.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnRoles.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnRoles.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnRoles.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnRoles.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnRoles.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnRoles.ForeColor = System.Drawing.Color.White;
            this.BtnRoles.IconLeft = global::Ice.Properties.Resources.people_poll;
            this.BtnRoles.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnRoles.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnRoles.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnRoles.IconMarginLeft = 11;
            this.BtnRoles.IconPadding = 10;
            this.BtnRoles.IconRight = null;
            this.BtnRoles.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnRoles.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnRoles.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnRoles.IconSize = 25;
            this.BtnRoles.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnRoles.IdleBorderRadius = 0;
            this.BtnRoles.IdleBorderThickness = 0;
            this.BtnRoles.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnRoles.IdleIconLeftImage = global::Ice.Properties.Resources.people_poll;
            this.BtnRoles.IdleIconRightImage = null;
            this.BtnRoles.IndicateFocus = false;
            this.BtnRoles.Location = new System.Drawing.Point(0, 237);
            this.BtnRoles.Name = "BtnRoles";
            this.BtnRoles.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnRoles.OnDisabledState.BorderRadius = 15;
            this.BtnRoles.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRoles.OnDisabledState.BorderThickness = 1;
            this.BtnRoles.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnRoles.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnRoles.OnDisabledState.IconLeftImage = null;
            this.BtnRoles.OnDisabledState.IconRightImage = null;
            this.BtnRoles.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnRoles.onHoverState.BorderRadius = 15;
            this.BtnRoles.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRoles.onHoverState.BorderThickness = 1;
            this.BtnRoles.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnRoles.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnRoles.onHoverState.IconLeftImage = null;
            this.BtnRoles.onHoverState.IconRightImage = null;
            this.BtnRoles.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnRoles.OnIdleState.BorderRadius = 15;
            this.BtnRoles.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRoles.OnIdleState.BorderThickness = 1;
            this.BtnRoles.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnRoles.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnRoles.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.people_poll;
            this.BtnRoles.OnIdleState.IconRightImage = null;
            this.BtnRoles.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnRoles.OnPressedState.BorderRadius = 15;
            this.BtnRoles.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnRoles.OnPressedState.BorderThickness = 1;
            this.BtnRoles.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnRoles.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnRoles.OnPressedState.IconLeftImage = null;
            this.BtnRoles.OnPressedState.IconRightImage = null;
            this.BtnRoles.Size = new System.Drawing.Size(228, 39);
            this.BtnRoles.TabIndex = 6;
            this.BtnRoles.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnRoles.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnRoles.TextMarginLeft = 0;
            this.BtnRoles.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnRoles.UseDefaultRadiusAndThickness = true;
            this.BtnRoles.Click += new System.EventHandler(this.BtnRoles_Click);
            // 
            // BtnEmpleados
            // 
            this.BtnEmpleados.AllowAnimations = true;
            this.BtnEmpleados.AllowMouseEffects = true;
            this.BtnEmpleados.AllowToggling = false;
            this.BtnEmpleados.AnimationSpeed = 200;
            this.BtnEmpleados.AutoGenerateColors = false;
            this.BtnEmpleados.AutoRoundBorders = false;
            this.BtnEmpleados.AutoSizeLeftIcon = true;
            this.BtnEmpleados.AutoSizeRightIcon = true;
            this.BtnEmpleados.BackColor = System.Drawing.Color.Transparent;
            this.BtnEmpleados.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnEmpleados.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnEmpleados.BackgroundImage")));
            this.BtnEmpleados.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEmpleados.ButtonText = "Empleados";
            this.BtnEmpleados.ButtonTextMarginLeft = 0;
            this.BtnEmpleados.ColorContrastOnClick = 45;
            this.BtnEmpleados.ColorContrastOnHover = 45;
            this.BtnEmpleados.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnEmpleados.CustomizableEdges = borderEdges5;
            this.SideBarTransition.SetDecoration(this.BtnEmpleados, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnEmpleados.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnEmpleados.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEmpleados.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnEmpleados.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnEmpleados.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnEmpleados.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnEmpleados.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnEmpleados.ForeColor = System.Drawing.Color.White;
            this.BtnEmpleados.IconLeft = global::Ice.Properties.Resources.briefcase;
            this.BtnEmpleados.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnEmpleados.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEmpleados.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnEmpleados.IconMarginLeft = 11;
            this.BtnEmpleados.IconPadding = 10;
            this.BtnEmpleados.IconRight = null;
            this.BtnEmpleados.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnEmpleados.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEmpleados.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnEmpleados.IconSize = 25;
            this.BtnEmpleados.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnEmpleados.IdleBorderRadius = 0;
            this.BtnEmpleados.IdleBorderThickness = 0;
            this.BtnEmpleados.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnEmpleados.IdleIconLeftImage = global::Ice.Properties.Resources.briefcase;
            this.BtnEmpleados.IdleIconRightImage = null;
            this.BtnEmpleados.IndicateFocus = false;
            this.BtnEmpleados.Location = new System.Drawing.Point(0, 198);
            this.BtnEmpleados.Name = "BtnEmpleados";
            this.BtnEmpleados.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEmpleados.OnDisabledState.BorderRadius = 15;
            this.BtnEmpleados.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEmpleados.OnDisabledState.BorderThickness = 1;
            this.BtnEmpleados.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEmpleados.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEmpleados.OnDisabledState.IconLeftImage = null;
            this.BtnEmpleados.OnDisabledState.IconRightImage = null;
            this.BtnEmpleados.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnEmpleados.onHoverState.BorderRadius = 15;
            this.BtnEmpleados.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEmpleados.onHoverState.BorderThickness = 1;
            this.BtnEmpleados.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnEmpleados.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnEmpleados.onHoverState.IconLeftImage = null;
            this.BtnEmpleados.onHoverState.IconRightImage = null;
            this.BtnEmpleados.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnEmpleados.OnIdleState.BorderRadius = 15;
            this.BtnEmpleados.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEmpleados.OnIdleState.BorderThickness = 1;
            this.BtnEmpleados.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnEmpleados.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnEmpleados.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.briefcase;
            this.BtnEmpleados.OnIdleState.IconRightImage = null;
            this.BtnEmpleados.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnEmpleados.OnPressedState.BorderRadius = 15;
            this.BtnEmpleados.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEmpleados.OnPressedState.BorderThickness = 1;
            this.BtnEmpleados.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnEmpleados.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnEmpleados.OnPressedState.IconLeftImage = null;
            this.BtnEmpleados.OnPressedState.IconRightImage = null;
            this.BtnEmpleados.Size = new System.Drawing.Size(228, 39);
            this.BtnEmpleados.TabIndex = 5;
            this.BtnEmpleados.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnEmpleados.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnEmpleados.TextMarginLeft = 0;
            this.BtnEmpleados.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnEmpleados.UseDefaultRadiusAndThickness = true;
            this.BtnEmpleados.Click += new System.EventHandler(this.BtnEmpleados_Click);
            // 
            // BtnProductos
            // 
            this.BtnProductos.AllowAnimations = true;
            this.BtnProductos.AllowMouseEffects = true;
            this.BtnProductos.AllowToggling = false;
            this.BtnProductos.AnimationSpeed = 200;
            this.BtnProductos.AutoGenerateColors = false;
            this.BtnProductos.AutoRoundBorders = false;
            this.BtnProductos.AutoSizeLeftIcon = true;
            this.BtnProductos.AutoSizeRightIcon = true;
            this.BtnProductos.BackColor = System.Drawing.Color.Transparent;
            this.BtnProductos.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnProductos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnProductos.BackgroundImage")));
            this.BtnProductos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProductos.ButtonText = "Productos";
            this.BtnProductos.ButtonTextMarginLeft = 0;
            this.BtnProductos.ColorContrastOnClick = 45;
            this.BtnProductos.ColorContrastOnHover = 45;
            this.BtnProductos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnProductos.CustomizableEdges = borderEdges6;
            this.SideBarTransition.SetDecoration(this.BtnProductos, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnProductos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnProductos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnProductos.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnProductos.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnProductos.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnProductos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnProductos.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnProductos.ForeColor = System.Drawing.Color.White;
            this.BtnProductos.IconLeft = global::Ice.Properties.Resources.boxes;
            this.BtnProductos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnProductos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnProductos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnProductos.IconMarginLeft = 11;
            this.BtnProductos.IconPadding = 10;
            this.BtnProductos.IconRight = null;
            this.BtnProductos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnProductos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnProductos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnProductos.IconSize = 25;
            this.BtnProductos.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnProductos.IdleBorderRadius = 0;
            this.BtnProductos.IdleBorderThickness = 0;
            this.BtnProductos.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnProductos.IdleIconLeftImage = global::Ice.Properties.Resources.boxes;
            this.BtnProductos.IdleIconRightImage = null;
            this.BtnProductos.IndicateFocus = false;
            this.BtnProductos.Location = new System.Drawing.Point(0, 159);
            this.BtnProductos.Name = "BtnProductos";
            this.BtnProductos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnProductos.OnDisabledState.BorderRadius = 15;
            this.BtnProductos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProductos.OnDisabledState.BorderThickness = 1;
            this.BtnProductos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnProductos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnProductos.OnDisabledState.IconLeftImage = null;
            this.BtnProductos.OnDisabledState.IconRightImage = null;
            this.BtnProductos.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnProductos.onHoverState.BorderRadius = 15;
            this.BtnProductos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProductos.onHoverState.BorderThickness = 1;
            this.BtnProductos.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnProductos.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnProductos.onHoverState.IconLeftImage = null;
            this.BtnProductos.onHoverState.IconRightImage = null;
            this.BtnProductos.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnProductos.OnIdleState.BorderRadius = 15;
            this.BtnProductos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProductos.OnIdleState.BorderThickness = 1;
            this.BtnProductos.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnProductos.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnProductos.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.boxes;
            this.BtnProductos.OnIdleState.IconRightImage = null;
            this.BtnProductos.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnProductos.OnPressedState.BorderRadius = 15;
            this.BtnProductos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProductos.OnPressedState.BorderThickness = 1;
            this.BtnProductos.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnProductos.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnProductos.OnPressedState.IconLeftImage = null;
            this.BtnProductos.OnPressedState.IconRightImage = null;
            this.BtnProductos.Size = new System.Drawing.Size(228, 39);
            this.BtnProductos.TabIndex = 4;
            this.BtnProductos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnProductos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnProductos.TextMarginLeft = 0;
            this.BtnProductos.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnProductos.UseDefaultRadiusAndThickness = true;
            this.BtnProductos.Click += new System.EventHandler(this.BtnProductos_Click);
            // 
            // BtnMateriasPrimas
            // 
            this.BtnMateriasPrimas.AllowAnimations = true;
            this.BtnMateriasPrimas.AllowMouseEffects = true;
            this.BtnMateriasPrimas.AllowToggling = false;
            this.BtnMateriasPrimas.AnimationSpeed = 200;
            this.BtnMateriasPrimas.AutoGenerateColors = false;
            this.BtnMateriasPrimas.AutoRoundBorders = false;
            this.BtnMateriasPrimas.AutoSizeLeftIcon = true;
            this.BtnMateriasPrimas.AutoSizeRightIcon = true;
            this.BtnMateriasPrimas.BackColor = System.Drawing.Color.Transparent;
            this.BtnMateriasPrimas.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnMateriasPrimas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnMateriasPrimas.BackgroundImage")));
            this.BtnMateriasPrimas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMateriasPrimas.ButtonText = "Materias Primas";
            this.BtnMateriasPrimas.ButtonTextMarginLeft = 0;
            this.BtnMateriasPrimas.ColorContrastOnClick = 45;
            this.BtnMateriasPrimas.ColorContrastOnHover = 45;
            this.BtnMateriasPrimas.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.BtnMateriasPrimas.CustomizableEdges = borderEdges7;
            this.SideBarTransition.SetDecoration(this.BtnMateriasPrimas, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnMateriasPrimas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnMateriasPrimas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnMateriasPrimas.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnMateriasPrimas.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnMateriasPrimas.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnMateriasPrimas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnMateriasPrimas.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnMateriasPrimas.ForeColor = System.Drawing.Color.White;
            this.BtnMateriasPrimas.IconLeft = global::Ice.Properties.Resources.hamburger_soda;
            this.BtnMateriasPrimas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnMateriasPrimas.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnMateriasPrimas.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnMateriasPrimas.IconMarginLeft = 11;
            this.BtnMateriasPrimas.IconPadding = 10;
            this.BtnMateriasPrimas.IconRight = null;
            this.BtnMateriasPrimas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnMateriasPrimas.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnMateriasPrimas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnMateriasPrimas.IconSize = 25;
            this.BtnMateriasPrimas.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnMateriasPrimas.IdleBorderRadius = 0;
            this.BtnMateriasPrimas.IdleBorderThickness = 0;
            this.BtnMateriasPrimas.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnMateriasPrimas.IdleIconLeftImage = global::Ice.Properties.Resources.hamburger_soda;
            this.BtnMateriasPrimas.IdleIconRightImage = null;
            this.BtnMateriasPrimas.IndicateFocus = false;
            this.BtnMateriasPrimas.Location = new System.Drawing.Point(0, 120);
            this.BtnMateriasPrimas.Name = "BtnMateriasPrimas";
            this.BtnMateriasPrimas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnMateriasPrimas.OnDisabledState.BorderRadius = 15;
            this.BtnMateriasPrimas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMateriasPrimas.OnDisabledState.BorderThickness = 1;
            this.BtnMateriasPrimas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnMateriasPrimas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnMateriasPrimas.OnDisabledState.IconLeftImage = null;
            this.BtnMateriasPrimas.OnDisabledState.IconRightImage = null;
            this.BtnMateriasPrimas.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnMateriasPrimas.onHoverState.BorderRadius = 15;
            this.BtnMateriasPrimas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMateriasPrimas.onHoverState.BorderThickness = 1;
            this.BtnMateriasPrimas.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnMateriasPrimas.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnMateriasPrimas.onHoverState.IconLeftImage = null;
            this.BtnMateriasPrimas.onHoverState.IconRightImage = null;
            this.BtnMateriasPrimas.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnMateriasPrimas.OnIdleState.BorderRadius = 15;
            this.BtnMateriasPrimas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMateriasPrimas.OnIdleState.BorderThickness = 1;
            this.BtnMateriasPrimas.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnMateriasPrimas.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnMateriasPrimas.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.hamburger_soda;
            this.BtnMateriasPrimas.OnIdleState.IconRightImage = null;
            this.BtnMateriasPrimas.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnMateriasPrimas.OnPressedState.BorderRadius = 15;
            this.BtnMateriasPrimas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnMateriasPrimas.OnPressedState.BorderThickness = 1;
            this.BtnMateriasPrimas.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnMateriasPrimas.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnMateriasPrimas.OnPressedState.IconLeftImage = null;
            this.BtnMateriasPrimas.OnPressedState.IconRightImage = null;
            this.BtnMateriasPrimas.Size = new System.Drawing.Size(228, 39);
            this.BtnMateriasPrimas.TabIndex = 3;
            this.BtnMateriasPrimas.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnMateriasPrimas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnMateriasPrimas.TextMarginLeft = 0;
            this.BtnMateriasPrimas.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnMateriasPrimas.UseDefaultRadiusAndThickness = true;
            this.BtnMateriasPrimas.Click += new System.EventHandler(this.BtnMateriasPrimas_Click);
            // 
            // BtnCategoriasProductos
            // 
            this.BtnCategoriasProductos.AllowAnimations = true;
            this.BtnCategoriasProductos.AllowMouseEffects = true;
            this.BtnCategoriasProductos.AllowToggling = false;
            this.BtnCategoriasProductos.AnimationSpeed = 200;
            this.BtnCategoriasProductos.AutoGenerateColors = false;
            this.BtnCategoriasProductos.AutoRoundBorders = false;
            this.BtnCategoriasProductos.AutoSizeLeftIcon = true;
            this.BtnCategoriasProductos.AutoSizeRightIcon = true;
            this.BtnCategoriasProductos.BackColor = System.Drawing.Color.Transparent;
            this.BtnCategoriasProductos.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCategoriasProductos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCategoriasProductos.BackgroundImage")));
            this.BtnCategoriasProductos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCategoriasProductos.ButtonText = "Categorías de Productos";
            this.BtnCategoriasProductos.ButtonTextMarginLeft = 0;
            this.BtnCategoriasProductos.ColorContrastOnClick = 45;
            this.BtnCategoriasProductos.ColorContrastOnHover = 45;
            this.BtnCategoriasProductos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.BtnCategoriasProductos.CustomizableEdges = borderEdges8;
            this.SideBarTransition.SetDecoration(this.BtnCategoriasProductos, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnCategoriasProductos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCategoriasProductos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCategoriasProductos.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCategoriasProductos.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCategoriasProductos.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnCategoriasProductos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCategoriasProductos.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCategoriasProductos.ForeColor = System.Drawing.Color.White;
            this.BtnCategoriasProductos.IconLeft = global::Ice.Properties.Resources.apps;
            this.BtnCategoriasProductos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCategoriasProductos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCategoriasProductos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCategoriasProductos.IconMarginLeft = 11;
            this.BtnCategoriasProductos.IconPadding = 10;
            this.BtnCategoriasProductos.IconRight = null;
            this.BtnCategoriasProductos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCategoriasProductos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCategoriasProductos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCategoriasProductos.IconSize = 25;
            this.BtnCategoriasProductos.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCategoriasProductos.IdleBorderRadius = 0;
            this.BtnCategoriasProductos.IdleBorderThickness = 0;
            this.BtnCategoriasProductos.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCategoriasProductos.IdleIconLeftImage = global::Ice.Properties.Resources.apps;
            this.BtnCategoriasProductos.IdleIconRightImage = null;
            this.BtnCategoriasProductos.IndicateFocus = false;
            this.BtnCategoriasProductos.Location = new System.Drawing.Point(0, 81);
            this.BtnCategoriasProductos.Name = "BtnCategoriasProductos";
            this.BtnCategoriasProductos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCategoriasProductos.OnDisabledState.BorderRadius = 15;
            this.BtnCategoriasProductos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCategoriasProductos.OnDisabledState.BorderThickness = 1;
            this.BtnCategoriasProductos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCategoriasProductos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCategoriasProductos.OnDisabledState.IconLeftImage = null;
            this.BtnCategoriasProductos.OnDisabledState.IconRightImage = null;
            this.BtnCategoriasProductos.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnCategoriasProductos.onHoverState.BorderRadius = 15;
            this.BtnCategoriasProductos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCategoriasProductos.onHoverState.BorderThickness = 1;
            this.BtnCategoriasProductos.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnCategoriasProductos.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnCategoriasProductos.onHoverState.IconLeftImage = null;
            this.BtnCategoriasProductos.onHoverState.IconRightImage = null;
            this.BtnCategoriasProductos.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnCategoriasProductos.OnIdleState.BorderRadius = 15;
            this.BtnCategoriasProductos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCategoriasProductos.OnIdleState.BorderThickness = 1;
            this.BtnCategoriasProductos.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnCategoriasProductos.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCategoriasProductos.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.apps;
            this.BtnCategoriasProductos.OnIdleState.IconRightImage = null;
            this.BtnCategoriasProductos.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnCategoriasProductos.OnPressedState.BorderRadius = 15;
            this.BtnCategoriasProductos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCategoriasProductos.OnPressedState.BorderThickness = 1;
            this.BtnCategoriasProductos.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnCategoriasProductos.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnCategoriasProductos.OnPressedState.IconLeftImage = null;
            this.BtnCategoriasProductos.OnPressedState.IconRightImage = null;
            this.BtnCategoriasProductos.Size = new System.Drawing.Size(228, 39);
            this.BtnCategoriasProductos.TabIndex = 2;
            this.BtnCategoriasProductos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCategoriasProductos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCategoriasProductos.TextMarginLeft = 0;
            this.BtnCategoriasProductos.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCategoriasProductos.UseDefaultRadiusAndThickness = true;
            this.BtnCategoriasProductos.Click += new System.EventHandler(this.BtnCategoriasProductos_Click);
            // 
            // BtnProveedores
            // 
            this.BtnProveedores.AllowAnimations = true;
            this.BtnProveedores.AllowMouseEffects = true;
            this.BtnProveedores.AllowToggling = false;
            this.BtnProveedores.AnimationSpeed = 200;
            this.BtnProveedores.AutoGenerateColors = false;
            this.BtnProveedores.AutoRoundBorders = false;
            this.BtnProveedores.AutoSizeLeftIcon = true;
            this.BtnProveedores.AutoSizeRightIcon = true;
            this.BtnProveedores.BackColor = System.Drawing.Color.Transparent;
            this.BtnProveedores.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnProveedores.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnProveedores.BackgroundImage")));
            this.BtnProveedores.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProveedores.ButtonText = "Proveedores";
            this.BtnProveedores.ButtonTextMarginLeft = 0;
            this.BtnProveedores.ColorContrastOnClick = 45;
            this.BtnProveedores.ColorContrastOnHover = 45;
            this.BtnProveedores.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.BtnProveedores.CustomizableEdges = borderEdges9;
            this.SideBarTransition.SetDecoration(this.BtnProveedores, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnProveedores.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnProveedores.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnProveedores.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnProveedores.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnProveedores.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnProveedores.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnProveedores.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnProveedores.ForeColor = System.Drawing.Color.White;
            this.BtnProveedores.IconLeft = global::Ice.Properties.Resources.truck_moving;
            this.BtnProveedores.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnProveedores.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnProveedores.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnProveedores.IconMarginLeft = 11;
            this.BtnProveedores.IconPadding = 10;
            this.BtnProveedores.IconRight = null;
            this.BtnProveedores.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnProveedores.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnProveedores.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnProveedores.IconSize = 25;
            this.BtnProveedores.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnProveedores.IdleBorderRadius = 0;
            this.BtnProveedores.IdleBorderThickness = 0;
            this.BtnProveedores.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnProveedores.IdleIconLeftImage = global::Ice.Properties.Resources.truck_moving;
            this.BtnProveedores.IdleIconRightImage = null;
            this.BtnProveedores.IndicateFocus = false;
            this.BtnProveedores.Location = new System.Drawing.Point(0, 42);
            this.BtnProveedores.Name = "BtnProveedores";
            this.BtnProveedores.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnProveedores.OnDisabledState.BorderRadius = 15;
            this.BtnProveedores.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProveedores.OnDisabledState.BorderThickness = 1;
            this.BtnProveedores.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnProveedores.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnProveedores.OnDisabledState.IconLeftImage = null;
            this.BtnProveedores.OnDisabledState.IconRightImage = null;
            this.BtnProveedores.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnProveedores.onHoverState.BorderRadius = 15;
            this.BtnProveedores.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProveedores.onHoverState.BorderThickness = 1;
            this.BtnProveedores.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnProveedores.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnProveedores.onHoverState.IconLeftImage = null;
            this.BtnProveedores.onHoverState.IconRightImage = null;
            this.BtnProveedores.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnProveedores.OnIdleState.BorderRadius = 15;
            this.BtnProveedores.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProveedores.OnIdleState.BorderThickness = 1;
            this.BtnProveedores.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnProveedores.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnProveedores.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.truck_moving;
            this.BtnProveedores.OnIdleState.IconRightImage = null;
            this.BtnProveedores.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnProveedores.OnPressedState.BorderRadius = 15;
            this.BtnProveedores.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnProveedores.OnPressedState.BorderThickness = 1;
            this.BtnProveedores.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnProveedores.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnProveedores.OnPressedState.IconLeftImage = null;
            this.BtnProveedores.OnPressedState.IconRightImage = null;
            this.BtnProveedores.Size = new System.Drawing.Size(228, 39);
            this.BtnProveedores.TabIndex = 1;
            this.BtnProveedores.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnProveedores.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnProveedores.TextMarginLeft = 0;
            this.BtnProveedores.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnProveedores.UseDefaultRadiusAndThickness = true;
            this.BtnProveedores.Click += new System.EventHandler(this.BtnProveedores_Click);
            // 
            // BtnCompras
            // 
            this.BtnCompras.AllowAnimations = true;
            this.BtnCompras.AllowMouseEffects = true;
            this.BtnCompras.AllowToggling = false;
            this.BtnCompras.AnimationSpeed = 200;
            this.BtnCompras.AutoGenerateColors = false;
            this.BtnCompras.AutoRoundBorders = false;
            this.BtnCompras.AutoSizeLeftIcon = true;
            this.BtnCompras.AutoSizeRightIcon = true;
            this.BtnCompras.BackColor = System.Drawing.Color.Transparent;
            this.BtnCompras.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCompras.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCompras.BackgroundImage")));
            this.BtnCompras.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCompras.ButtonText = "Compras";
            this.BtnCompras.ButtonTextMarginLeft = 0;
            this.BtnCompras.ColorContrastOnClick = 45;
            this.BtnCompras.ColorContrastOnHover = 45;
            this.BtnCompras.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.BtnCompras.CustomizableEdges = borderEdges10;
            this.SideBarTransition.SetDecoration(this.BtnCompras, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.BtnCompras.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCompras.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCompras.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCompras.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCompras.Dock = System.Windows.Forms.DockStyle.Top;
            this.BtnCompras.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCompras.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCompras.ForeColor = System.Drawing.Color.White;
            this.BtnCompras.IconLeft = global::Ice.Properties.Resources.shopping_cart;
            this.BtnCompras.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCompras.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCompras.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCompras.IconMarginLeft = 11;
            this.BtnCompras.IconPadding = 10;
            this.BtnCompras.IconRight = null;
            this.BtnCompras.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCompras.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCompras.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCompras.IconSize = 25;
            this.BtnCompras.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCompras.IdleBorderRadius = 0;
            this.BtnCompras.IdleBorderThickness = 0;
            this.BtnCompras.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCompras.IdleIconLeftImage = global::Ice.Properties.Resources.shopping_cart;
            this.BtnCompras.IdleIconRightImage = null;
            this.BtnCompras.IndicateFocus = false;
            this.BtnCompras.Location = new System.Drawing.Point(0, 0);
            this.BtnCompras.Name = "BtnCompras";
            this.BtnCompras.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCompras.OnDisabledState.BorderRadius = 15;
            this.BtnCompras.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCompras.OnDisabledState.BorderThickness = 1;
            this.BtnCompras.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCompras.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCompras.OnDisabledState.IconLeftImage = null;
            this.BtnCompras.OnDisabledState.IconRightImage = null;
            this.BtnCompras.onHoverState.BorderColor = System.Drawing.Color.White;
            this.BtnCompras.onHoverState.BorderRadius = 15;
            this.BtnCompras.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCompras.onHoverState.BorderThickness = 1;
            this.BtnCompras.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnCompras.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnCompras.onHoverState.IconLeftImage = null;
            this.BtnCompras.onHoverState.IconRightImage = null;
            this.BtnCompras.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnCompras.OnIdleState.BorderRadius = 15;
            this.BtnCompras.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCompras.OnIdleState.BorderThickness = 1;
            this.BtnCompras.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnCompras.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCompras.OnIdleState.IconLeftImage = global::Ice.Properties.Resources.shopping_cart;
            this.BtnCompras.OnIdleState.IconRightImage = null;
            this.BtnCompras.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnCompras.OnPressedState.BorderRadius = 15;
            this.BtnCompras.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCompras.OnPressedState.BorderThickness = 1;
            this.BtnCompras.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnCompras.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnCompras.OnPressedState.IconLeftImage = null;
            this.BtnCompras.OnPressedState.IconRightImage = null;
            this.BtnCompras.Size = new System.Drawing.Size(228, 42);
            this.BtnCompras.TabIndex = 0;
            this.BtnCompras.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCompras.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCompras.TextMarginLeft = 0;
            this.BtnCompras.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCompras.UseDefaultRadiusAndThickness = true;
            this.BtnCompras.Click += new System.EventHandler(this.BtnCompras_Click);
            // 
            // SideBarTransition
            // 
            this.SideBarTransition.AnimationType = Bunifu.UI.WinForms.BunifuAnimatorNS.AnimationType.HorizSlide;
            this.SideBarTransition.Cursor = null;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.SideBarTransition.DefaultAnimation = animation1;
            // 
            // PnlPrincipal
            // 
            this.SideBarTransition.SetDecoration(this.PnlPrincipal, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.PnlPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PnlPrincipal.Location = new System.Drawing.Point(228, 27);
            this.PnlPrincipal.Name = "PnlPrincipal";
            this.PnlPrincipal.Size = new System.Drawing.Size(657, 476);
            this.PnlPrincipal.TabIndex = 2;
            // 
            // FrmPrincipal
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(885, 503);
            this.Controls.Add(this.PnlPrincipal);
            this.Controls.Add(this.PnlSideBar);
            this.Controls.Add(this.PnlTopBar);
            this.SideBarTransition.SetDecoration(this, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "FrmPrincipal";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Principal";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FrmPrincipal_FormClosing);
            this.PnlTopBar.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PbMenu)).EndInit();
            this.PnlSideBar.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel PnlTopBar;
        private System.Windows.Forms.PictureBox PbMenu;
        private Bunifu.UI.WinForms.BunifuGradientPanel PnlSideBar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCompras;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnProveedores;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCategoriasProductos;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnMateriasPrimas;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnProductos;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnEmpleados;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnRoles;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnUsuarios;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnClientes;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnVentas;
        private Bunifu.UI.WinForms.BunifuTransition SideBarTransition;
        private System.Windows.Forms.Panel PnlPrincipal;
    }
}